#!/usr/bin/env python3
"""
Sync the "Eatouts I had gone" section from Rohit's shared Google Maps list.

Google offers no API for saved lists, so this renders the public shared-list
page in headless Chrome, parses the places out of the DOM, and rewrites:
  - assets/data/eatouts.json                (data record)
  - index.html between EATOUTS:START/END    (static markup)

Run locally:  python3 scripts/sync_eatouts.py
Run in CI:    .github/workflows/sync-eatouts.yml (every 6 hours)

Fail-safe: if the scrape yields no places (blocked IP, markup change),
the script exits non-zero and touches nothing.
"""

import html
import json
import re
import shutil
import subprocess
import sys
import tempfile
import urllib.parse
import urllib.request
from pathlib import Path

SHARE_URL = "https://maps.app.goo.gl/15Vi3PHz57bbX9aK9"
REPO_ROOT = Path(__file__).resolve().parent.parent
DATA_PATH = REPO_ROOT / "assets" / "data" / "eatouts.json"
INDEX_PATH = REPO_ROOT / "index.html"
START_MARK = "<!-- EATOUTS:START (generated by scripts/sync_eatouts.py — do not edit by hand) -->"
END_MARK = "<!-- EATOUTS:END -->"
MAX_SHOWN = 10  # the list page renders newest-first; show the latest few, link out for the rest

CHROME_CANDIDATES = [
    "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
    "google-chrome",
    "google-chrome-stable",
    "chromium-browser",
    "chromium",
]


def find_chrome():
    for candidate in CHROME_CANDIDATES:
        path = candidate if candidate.startswith("/") else shutil.which(candidate)
        if path and Path(path).exists():
            return path
    sys.exit("No Chrome/Chromium binary found.")


def resolve_share_url():
    """The goo.gl link 302s to the real placelists URL for simple user agents."""
    request = urllib.request.Request(SHARE_URL, headers={"User-Agent": "curl/8"}, method="HEAD")

    class NoRedirect(urllib.request.HTTPRedirectHandler):
        def redirect_request(self, *args, **kwargs):
            return None

    opener = urllib.request.build_opener(NoRedirect)
    try:
        opener.open(request, timeout=30)
    except urllib.error.HTTPError as error:
        location = error.headers.get("Location") or ""
        match = re.search(r"/maps/placelists/list/([A-Za-z0-9_-]+)", location)
        if match:
            # Drop the tracking params; keep only the share-visibility flag.
            return f"https://www.google.com/maps/placelists/list/{match.group(1)}?shh=CAE"
    sys.exit("Could not resolve the shared list URL from " + SHARE_URL)


def render_list_page(chrome, url):
    """Render the page and return the DOM. Chrome sometimes hangs after
    --dump-dom has already written the full document, so a timeout is not
    fatal — kill the process and use whatever stdout was captured."""
    with tempfile.TemporaryDirectory() as profile:
        process = subprocess.Popen(
            [
                chrome,
                "--headless=new",
                "--disable-gpu",
                "--no-sandbox",
                "--no-first-run",
                f"--user-data-dir={profile}",
                "--virtual-time-budget=15000",
                "--dump-dom",
                url + ("&" if "?" in url else "?") + "hl=en",
            ],
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL,
            text=True,
        )
        try:
            stdout, _ = process.communicate(timeout=120)
        except subprocess.TimeoutExpired:
            process.kill()
            stdout, _ = process.communicate()
    if len(stdout or "") < 10000:
        sys.exit(f"Chrome render produced only {len(stdout or '')} bytes.")
    return stdout


def parse_places(dom):
    """Each list item renders its name with the fontHeadlineSmall class,
    followed by rating, review count, and category text nodes."""
    places = []
    chunks = re.split(r'class="[^"]*fontHeadlineSmall[^"]*"[^>]*>', dom)[1:]
    for chunk in chunks:
        name_match = re.match(r"([^<]{2,90})<", chunk)
        if not name_match:
            continue
        name = html.unescape(name_match.group(1)).strip()
        texts = [html.unescape(t).strip() for t in re.findall(r">([^<>]{1,110})<", chunk[:4000])]
        rating = next((t for t in texts if re.fullmatch(r"[0-5]\.\d", t)), None)
        category = next(
            (
                t
                for t in texts
                if re.fullmatch(r"[A-Z][A-Za-z' &-]{2,60}", t)
                and t != name
                and not t.startswith(("Save", "Share", "Open", "Direction"))
            ),
            None,
        )
        places.append(
            {
                "name": name,
                "rating": rating,
                "category": category,
                "mapsUrl": "https://www.google.com/maps/search/?api=1&query="
                + urllib.parse.quote(name),
            }
        )
    title_match = re.search(r"<h1[^>]*>([^<]{2,80})</h1>", dom)
    title = html.unescape(title_match.group(1)).strip() if title_match else "Eatouts I had gone"
    count_match = re.search(r"([\d,]+)\s+places?\b", dom)
    total = int(count_match.group(1).replace(",", "")) if count_match else len(places)
    return title, places, max(total, len(places))


def build_cards_html(places, total):
    cards = []
    for place in places[:MAX_SHOWN]:
        meta_bits = []
        if place["category"]:
            meta_bits.append(f'<span class="eatout-category">{html.escape(place["category"])}</span>')
        if place["rating"]:
            meta_bits.append(
                f'<span class="eatout-rating">✦ {place["rating"]} on Google</span>'
            )
        meta = f'<p class="eatout-meta">{"".join(meta_bits)}</p>' if meta_bits else ""
        cards.append(
            "          "
            f'<a class="eatout-card" href="{html.escape(place["mapsUrl"])}" target="_blank" rel="noopener noreferrer">'
            f'<h3>{html.escape(place["name"])}</h3>{meta}'
            '<svg class="icon eatout-arrow" aria-hidden="true"><use href="#i-arrow-up-right"/></svg></a>'
        )
    remaining = total - min(len(places), MAX_SHOWN)
    if remaining > 0:
        cards.append(
            "          "
            f'<a class="eatout-card eatout-more" href="{html.escape(SHARE_URL)}" target="_blank" rel="noopener noreferrer">'
            f'<h3>+{remaining} more<span class="accent-dot">.</span></h3>'
            '<p class="eatout-meta"><span>The full trail, on Google Maps</span></p>'
            '<svg class="icon eatout-arrow" aria-hidden="true"><use href="#i-arrow-up-right"/></svg></a>'
        )
    return "\n".join(cards)


def main():
    chrome = find_chrome()
    list_url = resolve_share_url()
    dom = render_list_page(chrome, list_url)
    title, places, total = parse_places(dom)

    if len(places) < 3:
        sys.exit(f"Only {len(places)} places parsed — refusing to overwrite existing data.")

    DATA_PATH.parent.mkdir(parents=True, exist_ok=True)
    DATA_PATH.write_text(
        json.dumps({"listTitle": title, "shareUrl": SHARE_URL, "totalPlaces": total,
                    "places": places}, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )

    index = INDEX_PATH.read_text(encoding="utf-8")
    if START_MARK not in index or END_MARK not in index:
        sys.exit("EATOUTS markers not found in index.html.")
    before, rest = index.split(START_MARK, 1)
    _, after = rest.split(END_MARK, 1)
    generated = f"{START_MARK}\n{build_cards_html(places, total)}\n          {END_MARK}"
    INDEX_PATH.write_text(before + generated + after, encoding="utf-8")

    print(f"Synced {min(len(places), MAX_SHOWN)} of {total} places from “{title}”.")


if __name__ == "__main__":
    main()
